project_id = "zqapbmllkywsuywpfava"

[functions.blog-share]
verify_jwt = false

[functions.generate-lesson-quiz]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.send-receipt-email]
verify_jwt = false

[functions.fetch-education-news]
verify_jwt = false
